language: python

matrix:
  include:
  - python: '3.6'
    dist: xenial
  - python: '3.7'
    dist: xenial
  - python: 3.8-dev
    dist: xenial

  allow_failures:
  - python: 3.8-dev

before_install:
- apt-cache search libssl
- sudo apt-get install -y libpng16-16 libssl1.0.0

install:
- make install
- pip freeze

script:
- make lint
- make test
- make benchmark
- ./tests/check_tag.py
- python -c "import pydf; print(pydf.get_version())"

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: "mA/dvvqWF9yFuti868THNN81NueK9vvNYOokEMRHuabys2c5K1AtYw1SAUjZ/sNdkkgBtXNZB074J8wd3mi8RrsME++0rQmg8vhzsKwI43lE9pvc/jum8nezV7ZKhbT7jziEjv/AAS9s/8L2SJ6DWWaTJf4PDMCNYrAZZ0ySOwQ="
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
